[package]
name = "learn_rust"
version = "0.1.0"
authors = ["Qingxiang Jia <ybjqx3340@gmail.com>"]

[[bin]]
name = "udp_cmd"
path = "src/udp_cmd.rs"

[[bin]]
name = "serde_fun"
path = "src/serde_fun.rs"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"